AWSTemplateFormatVersion: '2010-09-09'
Description: MyFirst AWS CloudFormation Template

Parameters:
  BucketName:
    Description: The name of the S3 bucket
    Type: String

Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName

Outputs:
  BucketName:
    Description: The name of the created S3 bucket
    Value: !Ref MyBucket
